#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.
"""

import sys


def factorize(number):
    """
    Factorize as many numbers as possible into product of two smaller numbers.
    """
    for i in range(2, number // 2 + 1):
        if number % i == 0:
            return f"{number}={i}*{number//i}"
    return f"{number} is a prime number"


def process_file(file_path):
    """
    process_file processs files.
    """
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line.strip())
            result = factorize(number)
            print(result)


if __name__ == "__main__":
    """
    just a function.
    """
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    process_file(file_path)
