#!/usr/bin/python3

from sys import argv

def factorize(number):
    """
    Factorize a number into a product of two smaller numbers.
    """
    p = 2
    q = number // p
    print("{}={}*{}".format(number, p, q))

if len(argv) != 2:
    exit("Usage: factors <file>")

try:
    with open(argv[1]) as file:
        for line in file:
            number = int(line.strip())
            factorize(number)
except Exception as e:
    exit("An error occurred: {}".format(str(e)))
