#!/usr/bin/python3

from sys import argv

def factorize(number):
    """
    Factorize a number into a product of two smaller numbers.
    """
    p = 2
    while p * p <= number:
        if number % p == 0:
            q = number // p
            return "{}={}*{}".format(number, p, q)
        p += 1
    return "{} is prime".format(number)

if len(argv) != 2:
    exit("Usage: factors <file>")

try:
    with open(argv[1]) as file:
        for line in file:
            number = int(line.rstrip())
            print(factorize(number))
except Exception as e:
    print("An error occurred:", str(e))
