#!/usr/bin/env bash

check_factor() {
    num1=$2
    num2=$3

    if ((num2 > num1)); then
        numcp=$num1
        num1=$num2
        num2=$numcp
    fi

    echo "$1=$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r i; do
        number=$i
        factors=()
        
        for ((j=2; j<number; j++)); do
            if ((number % j == 0)); then
                factors=("$j" "$((number / j))")
                break
            fi
        done

        if [ ${#factors[@]} -eq 2 ]; then
            check_factor "$number" "${factors[@]}"
        fi
    done < "$1"
fi
